language: c

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT32
  - os: osx
    osx_image: xcode11
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: osx
    osx_image: xcode11
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32

script:
- rake test
