language: c

compiler:
- gcc
- clang
- cl

os:
- linux
- osx
- windows

env:
  global:
  - MRUBY_REPOSITORY=https://github.com/mruby/mruby.git
  - MRUBY_BRANCH=master
  matrix:
  - MRUBY_INT_SIZE=MRB_INT64
  - MRUBY_INT_SIZE=MRB_INT32

matrix:
  exclude:
  - os: linux
    compiler: cl
  - os: osx
    compiler: cl

addons:
  apt:
    packages:
    - bison
    - flex
  homebrew:
    packages:
    - bison
    - flex
    - gcc@7

before_install:
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    choco install winflexbison
  fi

before_script:
- git clone --branch ${MRUBY_BRANCH} --depth 1 ${MRUBY_REPOSITORY} mruby
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ] && [ "${TRAVIS_COMPILER}" = "gcc" ]; then
    export CC=gcc-7
    export CXX=gcc-7
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ] && [ "${TRAVIS_COMPILER}" = "cl" ]; then
    export PATH=$PATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    ls '/c/Program Files (x86)/Microsoft Visual Studio/2017'
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    export PATH=$PATH:"C:\ProgramData\chocolatey\lib\winflexbison\tools"
    export PATH=$PATH:"C:\tools\ruby25\bin"
    export YACC="win_bison.exe"
    env
  fi
- export MRUBY_TOOLCHAIN=${TRAVIS_COMPILER}
- echo MRUBY_TOOLCHAIN=$MRUBY_TOOLCHAIN
- echo MRUBY_INT_SIZE=$MRUBY_INT_SIZE

script:
- ruby mruby/minirake -f Rakefile -j 4 test
