language: c

compiler:
- gcc
- clang
- cl

os:
- linux
- osx
- windows

env:
  global:
  - MRUBY_REPOSITORY=https://github.com/mruby/mruby.git
  - MRUBY_BRANCH=master
  matrix:
  - MRUBY_INT_SIZE=MRB_INT64
  - MRUBY_INT_SIZE=MRB_INT32

matrix:
  exclude:
  - os: linux
    compiler: cl
  - os: osx
    compiler: cl

addons:
  apt:
    packages:
    - bison
    - flex
    update: true
  homebrew:
    packages:
    - bison
    - flex
    - gcc
    update: true

before_install:
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ] && [ "${TRAVIS_COMPILER}" = "gcc" ]; then
    ls -la "$(brew --prefix gcc)"
    ls -la "$(brew --prefix gcc)/bin"
    ls -la "$(brew --prefix gcc)/libexec/gcc"
    ls -la "$(brew --prefix gcc)/libexec/gcc/bin"
    export CC=gcc-9
    export CXX=gcc-9
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ] && [ "${TRAVIS_COMPILER}" = "cl" ]; then
    export PATH=$PATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    # ls '/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC'
    # ls '/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools'
    # ls '/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC'
    ls '/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023'
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    choco install winflexbison
    WINFLEXBISON_DIR="/c/ProgramData/chocolatey/lib/winflexbison/tools"
    cp "${WINFLEXBISON_DIR}/win_bison.exe" "${WINFLEXBISON_DIR}/bison.exe"
    export PATH=$PATH:"/c/ProgramData/chocolatey/lib/winflexbison/tools"
  fi

before_script:
- git clone --branch ${MRUBY_BRANCH} --depth 1 ${MRUBY_REPOSITORY} mruby
- export MRUBY_TOOLCHAIN=${TRAVIS_COMPILER}
- echo MRUBY_TOOLCHAIN=$MRUBY_TOOLCHAIN
- echo MRUBY_INT_SIZE=$MRUBY_INT_SIZE

script:
- ruby mruby/minirake -f Rakefile -j 4 test
