language: c

addons:
  apt:
    packages:
    - bison
    - flex
    update: true
  homebrew:
    packages:
    - bison
    - flex
    update: true

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT32
  - os: osx
    osx_image: xcode11
    compiler: gcc
    install:
    - brew install gcc-7
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
    - CC=gcc-7
    - CXX=gcc-7
  - os: osx
    osx_image: xcode11
    compiler: gcc
    install:
    - brew install gcc-7
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
    - CC=gcc-7
    - CXX=gcc-7
  - os: osx
    osx_image: xcode11
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: osx
    osx_image: xcode11
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: windows
    compiler: gcc
    install:
    - 'gem install rake'
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: windows
    compiler: gcc
    install:
    - 'gem install rake'
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: windows
    compiler: clang
    install:
    - 'gem install rake'
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT64
  - os: windows
    compiler: clang
    install:
    - 'gem install rake'
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT32
  - os: windows
    compiler: vscpp
    install:
    - 'gem install rake'
    env:
    - MRUBY_TOOLCHAIN=vscpp
    - MRUBY_INT_SIZE=MRB_INT64
  - os: windows
    compiler: vscpp
    install:
    - 'gem install rake'
    env:
    - MRUBY_TOOLCHAIN=vscpp
    - MRUBY_INT_SIZE=MRB_INT32

script:
- rake test
