language: c

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - bison
    - flex
    - rake

matrix:
  include:
  - os: linux
    dist: bionic
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: linux
    dist: bionic
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT32

script:
- rake test
