language: c

addons:
  apt:
    packages:
    - bison
    - flex
    update: true
  homebrew:
    packages:
    - bison
    - flex
    update: true

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    compiler: gcc
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT64
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=clang
    - MRUBY_INT_SIZE=MRB_INT32
  - os: osx
    osx_image: xcode11
    compiler: gcc
    install:
    - brew install gcc
    env:
    - CC=gcc-7
    - CXX=gcc-7
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: osx
    osx_image: xcode11
    compiler: gcc
    install:
    - brew install gcc
    env:
    - CC=gcc-7
    - CXX=gcc-7
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: osx
    osx_image: xcode11
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT64
  - os: osx
    osx_image: xcode11
    compiler: clang
    env:
    - MRUBY_TOOLCHAIN=gcc
    - MRUBY_INT_SIZE=MRB_INT32
  - os: windows
    env:
    - MRUBY_TOOLCHAIN=vscpp
    - MRUBY_INT_SIZE=MRB_INT64
  - os: windows
    env:
    - MRUBY_TOOLCHAIN=vscpp
    - MRUBY_INT_SIZE=MRB_INT32

script:
- ruby mruby/minirake -f Rakefile -j 4 test
