language: c

compiler:
- gcc
- clang
- vscpp

os:
- linux
- osx
- windows

env:
  matrix:
  - MRUBY_INT_SIZE=MRB_INT64
  - MRUBY_INT_SIZE=MRB_INT32

matrix:
  exclude:
  - os: linux
    compiler: vscpp
  - os: osx
    compiler: vscpp

addons:
  apt:
    packages:
    - bison
    - flex
    update: true
  homebrew:
    packages:
    - bison
    - flex
    update: true

before_install:
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew install gcc@7
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    choco install winflexbison
  fi

before_script:
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ] && [ "${TRAVIS_COMPILER}" = "gcc" ]; then
    export CC=gcc-7
    export CXX=gcc-7
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    echo 'rake test' >> build.bat
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    echo '@echo off' > build.bat
    echo 'rake test' > build.bat
    export PATH=$PATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    export PATH=$PATH:"C:\ProgramData\chocolatey\lib\winflexbison\tools"
    export PATH=$PATH:"C:\tools\ruby25\bin"
    export YACC="win_bison.exe"
    export BUILD_CMD="./build.bat"
  else
    export BUILD_CMD="rake test"
  fi
- export MRUBY_TOOLCHAIN=${TRAVIS_COMPILER}
- echo MRUBY_TOOLCHAIN=$MRUBY_TOOLCHAIN
- echo MRUBY_INT_SIZE=$MRUBY_INT_SIZE

script:
- ${BUILD_CMD}
