language: c

compiler:
- gcc
- clang
- cl

os:
# - linux
# - osx
- windows

dist: bionic
osx_image: xcode11

matrix:
  exclude:
  - os: linux
    compiler: cl
  - os: osx
    compiler: cl
  allow_failures:
  - os: windows
    compiler: gcc
  - os: windows
    compiler: clang

env:
  global:
  - MRUBY_REPOSITORY=https://github.com/mruby/mruby.git
  - MRUBY_BRANCH=master
  matrix:
  - MRUBY_INT_SIZE=MRB_INT64
  - MRUBY_INT_SIZE=MRB_INT32

before_install:
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ] && [ "${TRAVIS_COMPILER}" = "gcc" ]; then
    export CC=gcc-9
    export CXX=gcc-9
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    VC2017_REV="14.16.27023"
    UCRT_REV="10.0.17134.0"

    PROGRAM_DIR="/c/Program Files (x86)"

    VS2017_DIR="${PROGRAM_DIR}/Microsoft Visual Studio/2017"
    VC2017_DIR="${VS2017_DIR}/BuildTools/VC/Tools/MSVC/${VC2017_REV}"

    # VS2015_DIR="${PROGRAM_DIR}/Microsoft Visual Studio 14.0"
    # VC2015_DIR="${VS2015_DIR}/VC"

    WIN10SDK_DIR="${PROGRAM_DIR}/Windows Kits/10"

    export PATH=$PATH:"${VC2017_DIR}/bin/Hostx64/x64"

    export INCLUDE="${VC2017_DIR}/include"
    # export INCLUDE="${VC2015_DIR}/include":$INCLUDE
    export INCLUDE="${WIN10SDK_DIR}/Include/${UCRT_REV}/shared":$INCLUDE
    export INCLUDE="${WIN10SDK_DIR}/Include/${UCRT_REV}/ucrt":$INCLUDE
    export INCLUDE="${WIN10SDK_DIR}/Include/${UCRT_REV}/um":$INCLUDE

    export LIBPATH="${VC2017_DIR}/lib/x64"
    # export LIBPATH="${VC2015_DIR}/lib/amd64":$LIBPATH
    export LIBPATH="${WIN10SDK_DIR}/Lib/${UCRT_REV}/ucrt/x64":$LIBPATH
    export LIBPATH="${WIN10SDK_DIR}/Lib/${UCRT_REV}/um/x64":$LIBPATH

    export CL="/FS"

    # echo "####"
    # ls "/c/Program Files (x86)"
    # echo "####/MSBuild"
    # ls "/c/Program Files (x86)/MSBuild"
    # echo "####/Microsoft SDKs"
    # ls "/c/Program Files (x86)/Microsoft SDKs"
    # echo "####/Microsoft Visual Studio"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio"
    # echo "####/Microsoft Visual Studio/2017"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio/2017"
    # echo "####/Microsoft Visual Studio/2017/BuildTools"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools"
    # echo "####/Microsoft Visual Studio/2017/BuildTools/SDK"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/SDK"
    # echo "####/Microsoft Visual Studio/2017/BuildTools/VC"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC"
    # echo "####/Microsoft Visual Studio/2017/BuildTools/VC/Tools"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools"
    # echo "####/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC"
    # echo "####/Microsoft Visual Studio 14.0"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0"
    # echo "####/Microsoft Visual Studio 14.0/VC"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC"
    # echo "####/Microsoft Visual Studio 14.0/VC/bin"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin"
    # echo "####/Microsoft Visual Studio 14.0/VC/include"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"
    # echo "####/Microsoft Visual Studio 14.0/VC/lib"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib"
    # echo "####/Microsoft Visual Studio 14.0/VC/lib/amd64"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64"
    # echo "####/Windows Kits"
    # ls "/c/Program Files (x86)/Windows Kits"
    # echo "####/Windows Kits/10"
    # ls "/c/Program Files (x86)/Windows Kits/10"
    # echo "####/Windows Kits/10/Include"
    # ls "/c/Program Files (x86)/Windows Kits/10/Include"
    # echo "####/Windows Kits/10/Include/10.0.17134.0"
    # ls "/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0"
    # echo "####/Windows Kits/10/Include/10.0.17134.0/shared"
    # ls "/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/shared"
    # echo "####/Windows Kits/10/Include/10.0.17134.0/ucrt"
    # ls "/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/ucrt"
    # echo "####/Windows Kits/10/Include/10.0.17134.0/um"
    # ls "/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/um"
    # echo "####/Windows Kits/10/Lib"
    # ls "/c/Program Files (x86)/Windows Kits/10/Lib"
    # echo "####/Windows Kits/10/Lib/10.0.17134.0"
    # ls "/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0"
    # echo "####/Windows Kits/10/Lib/10.0.17134.0/ucrt"
    # ls "/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/ucrt"
    # echo "####/Windows Kits/10/Lib/10.0.17134.0/um"
    # ls "/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/um"
    # echo "####/Windows Kits/10/Lib/10.0.17134.0/um/x64"
    # ls "/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/um/x64"
    # echo "####/Windows Kits/10/Lib/10.0.17134.0/ucrt/x64"
    # ls "/c/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/ucrt/x64"
    # echo "####"

    choco install winflexbison
    WINFLEXBISON_DIR="/c/ProgramData/chocolatey/lib/winflexbison/tools"
    cp "${WINFLEXBISON_DIR}/win_bison.exe" "${WINFLEXBISON_DIR}/bison.exe"
    export PATH=$PATH:"${WINFLEXBISON_DIR}"
  fi

before_script:
- git clone --branch ${MRUBY_BRANCH} --depth 1 ${MRUBY_REPOSITORY} mruby
- export MRUBY_TOOLCHAIN=${TRAVIS_COMPILER}
- echo MRUBY_TOOLCHAIN=$MRUBY_TOOLCHAIN
- echo MRUBY_INT_SIZE=$MRUBY_INT_SIZE

script:
- ruby mruby/minirake -f Rakefile -j 4 all
- ruby mruby/minirake -f Rakefile -j 4 test
