language: c

compiler:
- gcc
- clang
- cl

os:
# - linux
# - osx
- windows

dist: bionic
osx_image: xcode11

matrix:
  exclude:
  - os: linux
    compiler: cl
  - os: osx
    compiler: cl
  allow_failures:
  - os: windows
    compiler: gcc
  - os: windows
    compiler: clang

env:
  global:
  - MRUBY_REPOSITORY=https://github.com/mruby/mruby.git
  - MRUBY_BRANCH=master
  matrix:
  - MRUBY_INT_SIZE=MRB_INT64
  - MRUBY_INT_SIZE=MRB_INT32

before_install:
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ] && [ "${TRAVIS_COMPILER}" = "gcc" ]; then
    export CC=gcc-9
    export CXX=gcc-9
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    VS2017DIR="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023"

    export PATH=$PATH:"${VS2017DIR}/bin/Hostx64/x64"
    export INCLUDE="${VS2017DIR}/include"
    export LIB="${VS2017DIR}/lib/x64"

    # echo "####"
    # ls "/c/Program Files (x86)"
    # echo "####/MSBuild"
    # ls "/c/Program Files (x86)/MSBuild"
    # echo "####/Microsoft SDKs"
    # ls "/c/Program Files (x86)/Microsoft SDKs"
    # echo "####/Microsoft Visual Studio"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio"
    # echo "####/Microsoft Visual Studio 14.0"
    # ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0"
    # echo "####/Windows Kits"
    # ls "/c/Program Files (x86)/Windows Kits"
    echo "####/Windows Kits/10"
    ls "/c/Program Files (x86)/Windows Kits/10"
    echo "####/Windows Kits/10/Include"
    ls "/c/Program Files (x86)/Windows Kits/10/Include"
    echo "####/Windows Kits/10/Include/10.0.17134.0"
    ls "/c/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0"
    echo "####/Windows Kits/10/Lib"
    ls "/c/Program Files (x86)/Windows Kits/10/Lib"
    echo "####"

    choco install winflexbison
    WINFLEXBISON_DIR="/c/ProgramData/chocolatey/lib/winflexbison/tools"
    cp "${WINFLEXBISON_DIR}/win_bison.exe" "${WINFLEXBISON_DIR}/bison.exe"
    export PATH=$PATH:"${WINFLEXBISON_DIR}"
  fi

before_script:
- git clone --branch ${MRUBY_BRANCH} --depth 1 ${MRUBY_REPOSITORY} mruby
- export MRUBY_TOOLCHAIN=${TRAVIS_COMPILER}
- echo MRUBY_TOOLCHAIN=$MRUBY_TOOLCHAIN
- echo MRUBY_INT_SIZE=$MRUBY_INT_SIZE

script:
- ruby mruby/minirake -f Rakefile -j 4 all
- ruby mruby/minirake -f Rakefile -j 4 test
